import { ApiProperty } from '@nestjs/swagger';

export class StartConversationDto {
  @ApiProperty({ description: 'ID of the listing this conversation is about', required: false })
  listingId?: string;

  @ApiProperty({ description: 'ID of the buyer user', required: false })
  buyerUserId?: string;

  @ApiProperty({ description: 'ID of the seller user', required: false })
  sellerUserId?: string;

  @ApiProperty({ description: 'Initial message text', required: false })
  initialText?: string;
}

export class UserMessageDto {
  @ApiProperty({ description: 'The message text content' })
  text: string;
}

export class MessageDto {
  @ApiProperty({ description: 'Unique identifier of the message' })
  id: string;

  @ApiProperty({ description: 'ID of the conversation this message belongs to' })
  conversationId: string;

  @ApiProperty({ enum: ['USER', 'AGENT', 'ADMIN'], description: 'Type of the message sender' })
  senderType: string;

  @ApiProperty({ description: 'The message content' })
  text: string;

  @ApiProperty({ description: 'Additional metadata in JSON format', required: false })
  metadata?: any;

  @ApiProperty({ type: Date, description: 'When the message was created' })
  createdAt: Date;
}

export class AgentRunDto {
  @ApiProperty({ description: 'Unique identifier of the agent run' })
  id: string;

  @ApiProperty({ description: 'ID of the conversation this run is associated with' })
  conversationId: string;

  @ApiProperty({ description: 'Input provided to the agent' })
  input: string;

  @ApiProperty({ description: 'Output generated by the agent' })
  output: string;

  @ApiProperty({ description: 'Decision made by the agent' })
  decision: string;

  @ApiProperty({ type: Date, description: 'When the agent run was created' })
  createdAt: Date;
}

export class DraftOrderDto {
  @ApiProperty({ description: 'Unique identifier of the draft order' })
  id: string;

  @ApiProperty({ description: 'ID of the conversation this draft order is associated with' })
  conversationId: string;

  @ApiProperty({ description: 'ID of the listing being ordered' })
  listingId: string;

  @ApiProperty({ description: 'ID of the buyer user' })
  buyerUserId: string;

  @ApiProperty({ description: 'ID of the seller user' })
  sellerUserId: string;

  @ApiProperty({ description: 'Quantity of items', default: 1 })
  quantity: number;

  @ApiProperty({ description: 'Agreed price', required: false })
  priceAgreed?: number;

  @ApiProperty({ 
    enum: ['DRAFT', 'PENDING', 'CONFIRMED', 'REJECTED'],
    default: 'DRAFT',
    description: 'Current status of the draft order'
  })
  status: string;

  @ApiProperty({ description: 'Shipping information', required: false })
  shippingInfo?: string;

  @ApiProperty({ type: Date, description: 'When the draft order was created' })
  createdAt: Date;

  @ApiProperty({ type: Date, description: 'When the draft order was last updated' })
  updatedAt: Date;
}

export class ConversationDto {
  @ApiProperty({ description: 'Unique identifier of the conversation' })
  id: string;

  @ApiProperty({ description: 'ID of the listing being discussed', required: false, nullable: true })
  listingId?: string | null;

  @ApiProperty({ description: 'ID of the buyer user', required: false })
  buyerUserId?: string;

  @ApiProperty({ description: 'ID of the seller user', required: false })
  sellerUserId?: string;

  @ApiProperty({ 
    enum: ['DRAFT', 'ACTIVE', 'COMPLETED', 'ARCHIVED'],
    default: 'DRAFT',
    description: 'Current status of the conversation'
  })
  status: string;

  @ApiProperty({ type: Date, description: 'When the conversation was created' })
  createdAt: Date;

  @ApiProperty({ type: Date, description: 'When the conversation was last updated' })
  updatedAt: Date;

  @ApiProperty({ type: [MessageDto], description: 'Messages in this conversation' })
  messages: MessageDto[];

  @ApiProperty({ type: [AgentRunDto], description: 'Agent runs associated with this conversation' })
  agentRuns: AgentRunDto[];

  @ApiProperty({ type: [DraftOrderDto], description: 'Draft orders created in this conversation' })
  draftOrders: DraftOrderDto[];
}
